resources:
  - name: production_redis_nodes
    type: elasticache_redis
    region: ap-northeast-1
    filters:
      tags:
        env: prod
      tag_conditions:
        - key: team
          operator: in
          values: [team-a, team-b]

outputs:
  - template: templates/redis-secrets.yaml.tmpl
    output_file: /etc/datadog-agent/conf.d/redisdb.d/conf.yaml
    on_empty: error
    data:
      resource_name: production_redis_nodes
