resources:
  - name: production_mysql_instances
    type: aurora_mysql
    region: ap-northeast-1
    filters:
      tags:
        env: prod

outputs:
  - template: templates/mysql.yaml.tmpl
    output_file: /tmp/dd-conf-gen/mysql-all.yaml
    on_empty: error
    data:
      resource_name: production_mysql_instances
  - template: templates/mysql-writer.yaml.tmpl
    output_file: /tmp/dd-conf-gen/mysql-writer.yaml
    on_empty: render
    data:
      resource_name: production_mysql_instances
